
CREATE TYPE IF NOT EXISTS train_timely AS ENUM
('Late', 'On Time', 'Completed', 'Early');

CREATE TYPE IF NOT EXISTS train_state AS ENUM
('Active', 'Completed');

/* 600 rows (545 exactly, according to wikipedia) */

CREATE TABLE IF NOT EXISTS stations (
    station_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(64) NOT NULL,
    code varchar(3) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);

/* approx 170 rows */

CREATE TABLE IF NOT EXISTS trains (
    train_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(128) NOT NULL,
    amtrak_train_number integer NOT NULL, /* unique per route direction */
    amtrak_object_id integer NOT NULL, /* unique per train */
    
    latitude double precision,
    longitude double precision,
    velocity double precision,
    heading varchar(2), /* cardinal directions */
    
    train_state train_state,
    train_timely train_timely,
    
    service_disruption boolean,
    original_scheduled_departure timestamp,
    updated_at timestamp
);

/* 3500 rows */

CREATE TABLE IF NOT EXISTS stations_trains (
    station_train_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    station_id integer REFERENCES stations, 
    train_id integer REFERENCES trains,
    scheduled_arrival timestamp,
    estimated_arrival timestamp,
    posted_arrival timestamp,
    scheduled_departure timestamp,
    estimated_departure timestamp,
    posted_departure timestamp
);
