DROP TABLE trains;

CREATE TABLE IF NOT EXISTS reports (
    train_report_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(128) NOT NULL,
    amtrak_train_number varchar(5) NOT NULL, /* unique per route direction */
    amtrak_object_id integer NOT NULL, /* unique per train */
    amtrak_next_station_id varchar(3),
    amtrak_last_station_id varchar(3),

    latitude double precision,
    longitude double precision,
    velocity double precision,
    heading varchar(2), /* cardinal directions */
    
    train_state train_state,
    train_timely train_timely,
    
    service_disruption boolean,
    original_scheduled_departure timestamp,
    updated_at timestamp
);
