ALTER TABLE stations ALTER COLUMN latitude DROP NOT NULL;
ALTER TABLE stations ALTER COLUMN longitude DROP NOT NULL;

INSERT INTO stations(name, station_id) VALUES ('Aberdeen','ABE');
INSERT INTO stations(name, station_id) VALUES ('Albany','ALY');
INSERT INTO stations(name, station_id) VALUES ('Albany–Rensselaer','ALB');
INSERT INTO stations(name, station_id) VALUES ('Albion','ALI');
INSERT INTO stations(name, station_id) VALUES ('Albuquerque','ABQ');
INSERT INTO stations(name, station_id) VALUES ('Aldershot','AST');
INSERT INTO stations(name, station_id) VALUES ('Alderson','ALD');
INSERT INTO stations(name, station_id) VALUES ('Alexandria','ALX');
INSERT INTO stations(name, station_id) VALUES ('Allensworth State Park','CNL');
INSERT INTO stations(name, station_id) VALUES ('Alliance','ALC');
INSERT INTO stations(name, station_id) VALUES ('Alpine','ALP');
INSERT INTO stations(name, station_id) VALUES ('Alton','ALN');
INSERT INTO stations(name, station_id) VALUES ('Altoona','ALT');
INSERT INTO stations(name, station_id) VALUES ('Amsterdam','AMS');
INSERT INTO stations(name, station_id) VALUES ('Anaheim','ANA');
INSERT INTO stations(name, station_id) VALUES ('Ann Arbor','ARB');
INSERT INTO stations(name, station_id) VALUES ('Anniston','ATN');
INSERT INTO stations(name, station_id) VALUES ('Antioch–Pittsburg','ACA');
INSERT INTO stations(name, station_id) VALUES ('Arcadia Valley','ACD');
INSERT INTO stations(name, station_id) VALUES ('Ardmore','ADM');
INSERT INTO stations(name, station_id) VALUES ('Ardmore','ARD');
INSERT INTO stations(name, station_id) VALUES ('Arkadelphia','ARK');
INSERT INTO stations(name, station_id) VALUES ('Ashland','AKY');
INSERT INTO stations(name, station_id) VALUES ('Ashland','ASD');
INSERT INTO stations(name, station_id) VALUES ('Atlanta Peachtree','ATL');
INSERT INTO stations(name, station_id) VALUES ('Auburn','ARN');
INSERT INTO stations(name, station_id) VALUES ('Austin','AUS');
INSERT INTO stations(name, station_id) VALUES ('Bakersfield','BFD');
INSERT INTO stations(name, station_id) VALUES ('Baltimore Penn','BAL');
INSERT INTO stations(name, station_id) VALUES ('Bangor','BAM');
INSERT INTO stations(name, station_id) VALUES ('Barstow','BAR');
INSERT INTO stations(name, station_id) VALUES ('Battle Creek','BTL');
INSERT INTO stations(name, station_id) VALUES ('Beaumont','BMT');
INSERT INTO stations(name, station_id) VALUES ('Bellingham Fairhaven','BEL');
INSERT INTO stations(name, station_id) VALUES ('Bellows Falls','BLF');
INSERT INTO stations(name, station_id) VALUES ('Benson','BEN');
INSERT INTO stations(name, station_id) VALUES ('Berkeley','BKY');
INSERT INTO stations(name, station_id) VALUES ('Berlin','BER');
INSERT INTO stations(name, station_id) VALUES ('Bingen–White Salmon','BNG');
INSERT INTO stations(name, station_id) VALUES ('Birmingham','BHM');
INSERT INTO stations(name, station_id) VALUES ('Bloomington–Normal','BNL');
INSERT INTO stations(name, station_id) VALUES ('Boston Back Bay','BBY');
INSERT INTO stations(name, station_id) VALUES ('Boston North','BON');
INSERT INTO stations(name, station_id) VALUES ('Boston South','BOS');
INSERT INTO stations(name, station_id) VALUES ('Brattleboro','BRA');
INSERT INTO stations(name, station_id) VALUES ('Bridgeport','BRP');
INSERT INTO stations(name, station_id) VALUES ('Brookhaven','BRH');
INSERT INTO stations(name, station_id) VALUES ('Browning','BRO');
INSERT INTO stations(name, station_id) VALUES ('Brunswick','BRK');
INSERT INTO stations(name, station_id) VALUES ('Bryan','BYN');
INSERT INTO stations(name, station_id) VALUES ('Buffalo–Depew','BUF');
INSERT INTO stations(name, station_id) VALUES ('Buffalo–Exchange Street','BFX');
INSERT INTO stations(name, station_id) VALUES ('Burbank Airport','BUR');
INSERT INTO stations(name, station_id) VALUES ('Burke Centre','BCV');
INSERT INTO stations(name, station_id) VALUES ('Burlington','BRL');
INSERT INTO stations(name, station_id) VALUES ('Burlington','BNC');
INSERT INTO stations(name, station_id) VALUES ('Burlington','BTN');
INSERT INTO stations(name, station_id) VALUES ('BWI Thurgood Marshall Airport','BWI');
INSERT INTO stations(name, station_id) VALUES ('Camarillo','CML');
INSERT INTO stations(name, station_id) VALUES ('Camden','CAM');
INSERT INTO stations(name, station_id) VALUES ('Carbondale','CDL');
INSERT INTO stations(name, station_id) VALUES ('Carlinville','CRV');
INSERT INTO stations(name, station_id) VALUES ('Carpinteria','CPN');
INSERT INTO stations(name, station_id) VALUES ('Cary','CYN');
INSERT INTO stations(name, station_id) VALUES ('Castleton','CNV');
INSERT INTO stations(name, station_id) VALUES ('Centralia','CEN');
INSERT INTO stations(name, station_id) VALUES ('Centralia','CTL');
INSERT INTO stations(name, station_id) VALUES ('Champaign–Urbana','CHM');
INSERT INTO stations(name, station_id) VALUES ('Charleston','CHS');
INSERT INTO stations(name, station_id) VALUES ('Charleston','CHW');
INSERT INTO stations(name, station_id) VALUES ('Charlotte','CLT');
INSERT INTO stations(name, station_id) VALUES ('Charlottesville','CVS');
INSERT INTO stations(name, station_id) VALUES ('Chatsworth','CWT');
INSERT INTO stations(name, station_id) VALUES ('Chemult','CMO');
INSERT INTO stations(name, station_id) VALUES ('Chicago Union','CHI');
INSERT INTO stations(name, station_id) VALUES ('Chico','CIC');
INSERT INTO stations(name, station_id) VALUES ('Cincinnati','CIN');
INSERT INTO stations(name, station_id) VALUES ('Claremont','CLA');
INSERT INTO stations(name, station_id) VALUES ('Cleburne','CBR');
INSERT INTO stations(name, station_id) VALUES ('Clemson','CSN');
INSERT INTO stations(name, station_id) VALUES ('Cleveland','CLE');
INSERT INTO stations(name, station_id) VALUES ('Clifton Forge','CLF');
INSERT INTO stations(name, station_id) VALUES ('Coatesville','COT');
INSERT INTO stations(name, station_id) VALUES ('Colfax','COX');
INSERT INTO stations(name, station_id) VALUES ('Columbia','CLB');
INSERT INTO stations(name, station_id) VALUES ('Columbus','CBS');
INSERT INTO stations(name, station_id) VALUES ('Connellsville','COV');
INSERT INTO stations(name, station_id) VALUES ('Connersville','COI');
INSERT INTO stations(name, station_id) VALUES ('Corcoran','COC');
INSERT INTO stations(name, station_id) VALUES ('Cornwells Heights','CWH');
INSERT INTO stations(name, station_id) VALUES ('Crawfordsville','CRF');
INSERT INTO stations(name, station_id) VALUES ('Creston','CRN');
INSERT INTO stations(name, station_id) VALUES ('Croton–Harmon','CRT');
INSERT INTO stations(name, station_id) VALUES ('Culpeper','CLP');
INSERT INTO stations(name, station_id) VALUES ('Cumberland','CUM');
INSERT INTO stations(name, station_id) VALUES ('Cut Bank','CUT');
INSERT INTO stations(name, station_id) VALUES ('Dallas','DAL');
INSERT INTO stations(name, station_id) VALUES ('Danville','DAN');
INSERT INTO stations(name, station_id) VALUES ('Davis','DAV');
INSERT INTO stations(name, station_id) VALUES ('Dearborn','DER');
INSERT INTO stations(name, station_id) VALUES ('Deerfield Beach','DFB');
INSERT INTO stations(name, station_id) VALUES ('Del Rio','DRT');
INSERT INTO stations(name, station_id) VALUES ('DeLand','DLD');
INSERT INTO stations(name, station_id) VALUES ('Delray Beach','DLB');
INSERT INTO stations(name, station_id) VALUES ('Deming','DEM');
INSERT INTO stations(name, station_id) VALUES ('Denmark','DNK');
INSERT INTO stations(name, station_id) VALUES ('Denver','DEN');
INSERT INTO stations(name, station_id) VALUES ('Detroit','DET');
INSERT INTO stations(name, station_id) VALUES ('Detroit Lakes','DLK');
INSERT INTO stations(name, station_id) VALUES ('Devils Lake','DVL');
INSERT INTO stations(name, station_id) VALUES ('Dillon','DIL');
INSERT INTO stations(name, station_id) VALUES ('Dodge City','DDG');
INSERT INTO stations(name, station_id) VALUES ('Dover','DOV');
INSERT INTO stations(name, station_id) VALUES ('Dowagiac','DOA');
INSERT INTO stations(name, station_id) VALUES ('Downingtown','DOW');
INSERT INTO stations(name, station_id) VALUES ('Du Quoin','DQN');
INSERT INTO stations(name, station_id) VALUES ('Dunsmuir','DUN');
INSERT INTO stations(name, station_id) VALUES ('Durand','DRD');
INSERT INTO stations(name, station_id) VALUES ('Durham','DNC');
INSERT INTO stations(name, station_id) VALUES ('Durham–UNH','DHM');
INSERT INTO stations(name, station_id) VALUES ('Dwight','DWT');
INSERT INTO stations(name, station_id) VALUES ('Dyer','DYE');
INSERT INTO stations(name, station_id) VALUES ('East Glacier Park','GPK');
INSERT INTO stations(name, station_id) VALUES ('East Lansing','LNS');
INSERT INTO stations(name, station_id) VALUES ('Edmonds','EDM');
INSERT INTO stations(name, station_id) VALUES ('Effingham','EFG');
INSERT INTO stations(name, station_id) VALUES ('El Paso','ELP');
INSERT INTO stations(name, station_id) VALUES ('Elkhart','EKH');
INSERT INTO stations(name, station_id) VALUES ('Elizabethtown','ELT');
INSERT INTO stations(name, station_id) VALUES ('Elko','ELK');
INSERT INTO stations(name, station_id) VALUES ('Elyria','ELY');
INSERT INTO stations(name, station_id) VALUES ('Emeryville','EMY');
INSERT INTO stations(name, station_id) VALUES ('Ephrata','EPH');
INSERT INTO stations(name, station_id) VALUES ('Erie','ERI');
INSERT INTO stations(name, station_id) VALUES ('Essex','ESM');
INSERT INTO stations(name, station_id) VALUES ('Essex Junction','ESX');
INSERT INTO stations(name, station_id) VALUES ('Eugene–Springfield','EUG');
INSERT INTO stations(name, station_id) VALUES ('Everett','EVR');
INSERT INTO stations(name, station_id) VALUES ('Exeter','EXR');
INSERT INTO stations(name, station_id) VALUES ('Exton','EXT');
INSERT INTO stations(name, station_id) VALUES ('Fairfield–Vacaville','FFV');
INSERT INTO stations(name, station_id) VALUES ('Fargo','FAR');
INSERT INTO stations(name, station_id) VALUES ('Fayetteville','FAY');
INSERT INTO stations(name, station_id) VALUES ('Ferrisburgh–Vergennes','VRN');
INSERT INTO stations(name, station_id) VALUES ('Flagstaff','FLG');
INSERT INTO stations(name, station_id) VALUES ('Flint','FLN');
INSERT INTO stations(name, station_id) VALUES ('Florence','FLO');
INSERT INTO stations(name, station_id) VALUES ('Fort Edward','FED');
INSERT INTO stations(name, station_id) VALUES ('Fort Lauderdale','FTL');
INSERT INTO stations(name, station_id) VALUES ('Fort Madison','FMD');
INSERT INTO stations(name, station_id) VALUES ('Fort Morgan','FMG');
INSERT INTO stations(name, station_id) VALUES ('Fort Worth','FTW');
INSERT INTO stations(name, station_id) VALUES ('Framingham','FRA');
INSERT INTO stations(name, station_id) VALUES ('Fraser–Winter Park','WIP');
INSERT INTO stations(name, station_id) VALUES ('Fredericksburg','FBG');
INSERT INTO stations(name, station_id) VALUES ('Freeport','FRE');
INSERT INTO stations(name, station_id) VALUES ('Fremont','FMT');
INSERT INTO stations(name, station_id) VALUES ('Fresno','FNO');
INSERT INTO stations(name, station_id) VALUES ('Fullerton','FUL');
INSERT INTO stations(name, station_id) VALUES ('Fulton','FTN');
INSERT INTO stations(name, station_id) VALUES ('Gainesville','GNS');
INSERT INTO stations(name, station_id) VALUES ('Gainesville','GLE');
INSERT INTO stations(name, station_id) VALUES ('Galesburg','GBB');
INSERT INTO stations(name, station_id) VALUES ('Gallup','GLP');
INSERT INTO stations(name, station_id) VALUES ('Garden City','GCK');
INSERT INTO stations(name, station_id) VALUES ('Gastonia','GAS');
INSERT INTO stations(name, station_id) VALUES ('Gilman','GLM');
INSERT INTO stations(name, station_id) VALUES ('Glasgow','GGW');
INSERT INTO stations(name, station_id) VALUES ('Glendale','GDL');
INSERT INTO stations(name, station_id) VALUES ('Glenview','GLN');
INSERT INTO stations(name, station_id) VALUES ('Glenwood Springs','GSC');
INSERT INTO stations(name, station_id) VALUES ('Goleta','GTA');
INSERT INTO stations(name, station_id) VALUES ('Granby','GRA');
INSERT INTO stations(name, station_id) VALUES ('Grand Forks','GFK');
INSERT INTO stations(name, station_id) VALUES ('Grand Junction','GJT');
INSERT INTO stations(name, station_id) VALUES ('Grand Rapids','GRR');
INSERT INTO stations(name, station_id) VALUES ('Green River','GRI');
INSERT INTO stations(name, station_id) VALUES ('Greenfield','GFD');
INSERT INTO stations(name, station_id) VALUES ('Greensboro','GRO');
INSERT INTO stations(name, station_id) VALUES ('Greensburg','GNB');
INSERT INTO stations(name, station_id) VALUES ('Greenville','GRV');
INSERT INTO stations(name, station_id) VALUES ('Greenwood','GWD');
INSERT INTO stations(name, station_id) VALUES ('Grimsby','GMS');
INSERT INTO stations(name, station_id) VALUES ('Grover Beach','GVB');
INSERT INTO stations(name, station_id) VALUES ('Guadalupe','GUA');
INSERT INTO stations(name, station_id) VALUES ('Hamlet','HAM');
INSERT INTO stations(name, station_id) VALUES ('Hammond','HMD');
INSERT INTO stations(name, station_id) VALUES ('Hammond/Whiting','HMI');
INSERT INTO stations(name, station_id) VALUES ('Hanford','HNF');
INSERT INTO stations(name, station_id) VALUES ('Harpers Ferry','HFY');
INSERT INTO stations(name, station_id) VALUES ('Harrisburg','HAR');
INSERT INTO stations(name, station_id) VALUES ('Hartford','HFD');
INSERT INTO stations(name, station_id) VALUES ('Hastings','HAS');
INSERT INTO stations(name, station_id) VALUES ('Hattiesburg','HBG');
INSERT INTO stations(name, station_id) VALUES ('Haverhill','HHL');
INSERT INTO stations(name, station_id) VALUES ('Havre','HAV');
INSERT INTO stations(name, station_id) VALUES ('Hayward','HAY');
INSERT INTO stations(name, station_id) VALUES ('Hazlehurst','HAZ');
INSERT INTO stations(name, station_id) VALUES ('Helper','HER');
INSERT INTO stations(name, station_id) VALUES ('Hermann','HEM');
INSERT INTO stations(name, station_id) VALUES ('High Point','HPT');
INSERT INTO stations(name, station_id) VALUES ('Hinton','HIN');
INSERT INTO stations(name, station_id) VALUES ('Holdrege','HLD');
INSERT INTO stations(name, station_id) VALUES ('Holland','HOM');
INSERT INTO stations(name, station_id) VALUES ('Hollywood','HOL');
INSERT INTO stations(name, station_id) VALUES ('Holyoke','HLK');
INSERT INTO stations(name, station_id) VALUES ('Homewood','HMW');
INSERT INTO stations(name, station_id) VALUES ('Hope','HOP');
INSERT INTO stations(name, station_id) VALUES ('Houston','HOS');
INSERT INTO stations(name, station_id) VALUES ('Hudson','HUD');
INSERT INTO stations(name, station_id) VALUES ('Huntingdon','HGD');
INSERT INTO stations(name, station_id) VALUES ('Huntington','HUN');
INSERT INTO stations(name, station_id) VALUES ('Hutchinson','HUT');
INSERT INTO stations(name, station_id) VALUES ('Independence','IDP');
INSERT INTO stations(name, station_id) VALUES ('Indianapolis','IND');
INSERT INTO stations(name, station_id) VALUES ('Irvine','IRV');
INSERT INTO stations(name, station_id) VALUES ('Jackson','JXN');
INSERT INTO stations(name, station_id) VALUES ('Jackson','JAN');
INSERT INTO stations(name, station_id) VALUES ('Jacksonville','JAX');
INSERT INTO stations(name, station_id) VALUES ('Jefferson City','JEF');
INSERT INTO stations(name, station_id) VALUES ('Jesup','JSP');
INSERT INTO stations(name, station_id) VALUES ('Johnstown','JST');
INSERT INTO stations(name, station_id) VALUES ('Joliet','JOL');
INSERT INTO stations(name, station_id) VALUES ('Kalamazoo','KAL');
INSERT INTO stations(name, station_id) VALUES ('Kankakee','KKI');
INSERT INTO stations(name, station_id) VALUES ('Kannapolis','KAN');
INSERT INTO stations(name, station_id) VALUES ('Kansas City','KCY');
INSERT INTO stations(name, station_id) VALUES ('Kelso','KEL');
INSERT INTO stations(name, station_id) VALUES ('Kewanee','KEE');
INSERT INTO stations(name, station_id) VALUES ('Kingman','KNG');
INSERT INTO stations(name, station_id) VALUES ('Kingston','KIN');
INSERT INTO stations(name, station_id) VALUES ('Kingstree','KTR');
INSERT INTO stations(name, station_id) VALUES ('Kirkwood','KWD');
INSERT INTO stations(name, station_id) VALUES ('Kissimmee','KIS');
INSERT INTO stations(name, station_id) VALUES ('Klamath Falls','KFS');
INSERT INTO stations(name, station_id) VALUES ('La Crosse','LSE');
INSERT INTO stations(name, station_id) VALUES ('La Grange Road','LAG');
INSERT INTO stations(name, station_id) VALUES ('La Junta','LAJ');
INSERT INTO stations(name, station_id) VALUES ('La Plata','LAP');
INSERT INTO stations(name, station_id) VALUES ('Lafayette','LAF');
INSERT INTO stations(name, station_id) VALUES ('Lafayette','LFT');
INSERT INTO stations(name, station_id) VALUES ('Lake Charles','LCH');
INSERT INTO stations(name, station_id) VALUES ('Lakeland','LKL');
INSERT INTO stations(name, station_id) VALUES ('Lakeland','LAK');
INSERT INTO stations(name, station_id) VALUES ('Lamar','LMR');
INSERT INTO stations(name, station_id) VALUES ('Lamy','LMY');
INSERT INTO stations(name, station_id) VALUES ('Lancaster','LNC');
INSERT INTO stations(name, station_id) VALUES ('Lapeer','LPE');
INSERT INTO stations(name, station_id) VALUES ('Las Vegas','LSV');
INSERT INTO stations(name, station_id) VALUES ('Latrobe','LAB');
INSERT INTO stations(name, station_id) VALUES ('Laurel','LAU');
INSERT INTO stations(name, station_id) VALUES ('Lawrence','LRC');
INSERT INTO stations(name, station_id) VALUES ('Leavenworth','LWA');
INSERT INTO stations(name, station_id) VALUES ('Lee''s Summit','LEE');
INSERT INTO stations(name, station_id) VALUES ('Lewistown','LEW');
INSERT INTO stations(name, station_id) VALUES ('Lexington','LEX');
INSERT INTO stations(name, station_id) VALUES ('Libby','LIB');
INSERT INTO stations(name, station_id) VALUES ('Lincoln','LCN');
INSERT INTO stations(name, station_id) VALUES ('Lincoln','LNK');
INSERT INTO stations(name, station_id) VALUES ('Little Rock','LRK');
INSERT INTO stations(name, station_id) VALUES ('Lodi','LOD');
INSERT INTO stations(name, station_id) VALUES ('Lompoc–Surf','LPS');
INSERT INTO stations(name, station_id) VALUES ('Longview','LVW');
INSERT INTO stations(name, station_id) VALUES ('Lordsburg','LDB');
INSERT INTO stations(name, station_id) VALUES ('Lorton','LOR');
INSERT INTO stations(name, station_id) VALUES ('Los Angeles Union','LAX');
INSERT INTO stations(name, station_id) VALUES ('Lynchburg–Kemper Street','LYH');
INSERT INTO stations(name, station_id) VALUES ('Macomb','MAC');
INSERT INTO stations(name, station_id) VALUES ('Madera','MDR');
INSERT INTO stations(name, station_id) VALUES ('Malta','MAL');
INSERT INTO stations(name, station_id) VALUES ('Malvern','MVN');
INSERT INTO stations(name, station_id) VALUES ('Manassas','MSS');
INSERT INTO stations(name, station_id) VALUES ('Maricopa','MRC');
INSERT INTO stations(name, station_id) VALUES ('Marks','MKS');
INSERT INTO stations(name, station_id) VALUES ('Marshall','MHL');
INSERT INTO stations(name, station_id) VALUES ('Martinez','MTZ');
INSERT INTO stations(name, station_id) VALUES ('Martinsburg','MRB');
INSERT INTO stations(name, station_id) VALUES ('Mattoon','MAT');
INSERT INTO stations(name, station_id) VALUES ('Maysville','MAY');
INSERT INTO stations(name, station_id) VALUES ('McComb','MCB');
INSERT INTO stations(name, station_id) VALUES ('McCook','MCK');
INSERT INTO stations(name, station_id) VALUES ('McGregor','MCG');
INSERT INTO stations(name, station_id) VALUES ('Memphis Central','MEM');
INSERT INTO stations(name, station_id) VALUES ('Mendota','MDT');
INSERT INTO stations(name, station_id) VALUES ('Merced','MCD');
INSERT INTO stations(name, station_id) VALUES ('Meriden','MDN');
INSERT INTO stations(name, station_id) VALUES ('Meridian','MEI');
INSERT INTO stations(name, station_id) VALUES ('Metropark','MET');
INSERT INTO stations(name, station_id) VALUES ('Miami','MIA');
INSERT INTO stations(name, station_id) VALUES ('Middlebury','MBY');
INSERT INTO stations(name, station_id) VALUES ('Middletown','MID');
INSERT INTO stations(name, station_id) VALUES ('Milwaukee','MKE');
INSERT INTO stations(name, station_id) VALUES ('Milwaukee Airport','MKA');
INSERT INTO stations(name, station_id) VALUES ('Mineola','MIN');
INSERT INTO stations(name, station_id) VALUES ('Minot','MOT');
INSERT INTO stations(name, station_id) VALUES ('Modesto','MOD');
INSERT INTO stations(name, station_id) VALUES ('Montgomery','MNG');
INSERT INTO stations(name, station_id) VALUES ('Montpelier','MPR');
INSERT INTO stations(name, station_id) VALUES ('Montreal','MTR');
INSERT INTO stations(name, station_id) VALUES ('Moorpark','MPK');
INSERT INTO stations(name, station_id) VALUES ('Mount Joy','MJY');
INSERT INTO stations(name, station_id) VALUES ('Mount Pleasant','MTP');
INSERT INTO stations(name, station_id) VALUES ('Mount Vernon','MVW');
INSERT INTO stations(name, station_id) VALUES ('Mystic','MYS');
INSERT INTO stations(name, station_id) VALUES ('Naperville','NPV');
INSERT INTO stations(name, station_id) VALUES ('Needles','NDL');
INSERT INTO stations(name, station_id) VALUES ('New Brunswick','NBK');
INSERT INTO stations(name, station_id) VALUES ('New Buffalo','NBU');
INSERT INTO stations(name, station_id) VALUES ('New Carrollton','NCR');
INSERT INTO stations(name, station_id) VALUES ('New Haven Union','NHV');
INSERT INTO stations(name, station_id) VALUES ('New Haven State Street','STS');
INSERT INTO stations(name, station_id) VALUES ('New Iberia','NIB');
INSERT INTO stations(name, station_id) VALUES ('New London','NLC');
INSERT INTO stations(name, station_id) VALUES ('New Orleans','NOL');
INSERT INTO stations(name, station_id) VALUES ('New Rochelle','NRO');
INSERT INTO stations(name, station_id) VALUES ('New York Penn','NYP');
INSERT INTO stations(name, station_id) VALUES ('New York State Fair','NYF');
INSERT INTO stations(name, station_id) VALUES ('Newark','NRK');
INSERT INTO stations(name, station_id) VALUES ('Newark Liberty International Airport','EWR');
INSERT INTO stations(name, station_id) VALUES ('Newark Penn','NWK');
INSERT INTO stations(name, station_id) VALUES ('Newbern–Dyersburg','NBN');
INSERT INTO stations(name, station_id) VALUES ('Newport News','NPN');
INSERT INTO stations(name, station_id) VALUES ('Newton','NEW');
INSERT INTO stations(name, station_id) VALUES ('Niagara Falls','NFL');
INSERT INTO stations(name, station_id) VALUES ('Niagara Falls','NFS');
INSERT INTO stations(name, station_id) VALUES ('Niles','NLS');
INSERT INTO stations(name, station_id) VALUES ('Norfolk','NFK');
INSERT INTO stations(name, station_id) VALUES ('Norman','NOR');
INSERT INTO stations(name, station_id) VALUES ('North Carolina State Fair','NSF');
INSERT INTO stations(name, station_id) VALUES ('Northampton','NHT');
INSERT INTO stations(name, station_id) VALUES ('Oakland Coliseum','OAC');
INSERT INTO stations(name, station_id) VALUES ('Oakland–Jack London Square','OKJ');
INSERT INTO stations(name, station_id) VALUES ('Oakville','OKL');
INSERT INTO stations(name, station_id) VALUES ('Oceanside','OSD');
INSERT INTO stations(name, station_id) VALUES ('Okeechobee','OKE');
INSERT INTO stations(name, station_id) VALUES ('Oklahoma City','OKC');
INSERT INTO stations(name, station_id) VALUES ('Old Orchard Beach','ORB');
INSERT INTO stations(name, station_id) VALUES ('Old Saybrook','OSB');
INSERT INTO stations(name, station_id) VALUES ('Olympia–Lacey','OLW');
INSERT INTO stations(name, station_id) VALUES ('Omaha','OMA');
INSERT INTO stations(name, station_id) VALUES ('Ontario','ONA');
INSERT INTO stations(name, station_id) VALUES ('Oregon City','ORC');
INSERT INTO stations(name, station_id) VALUES ('Orlando','ORL');
INSERT INTO stations(name, station_id) VALUES ('Osceola','OSC');
INSERT INTO stations(name, station_id) VALUES ('Ottumwa','OTM');
INSERT INTO stations(name, station_id) VALUES ('Oxnard','OXN');
INSERT INTO stations(name, station_id) VALUES ('Palatka','PAK');
INSERT INTO stations(name, station_id) VALUES ('Palm Springs','PSN');
INSERT INTO stations(name, station_id) VALUES ('Paoli','PAO');
INSERT INTO stations(name, station_id) VALUES ('Parkesburg','PAR');
INSERT INTO stations(name, station_id) VALUES ('Pasco','PSC');
INSERT INTO stations(name, station_id) VALUES ('Paso Robles','PRB');
INSERT INTO stations(name, station_id) VALUES ('Petersburg','PTB');
INSERT INTO stations(name, station_id) VALUES ('Pauls Valley','PVL');
INSERT INTO stations(name, station_id) VALUES ('Philadelphia 30th Street','PHL');
INSERT INTO stations(name, station_id) VALUES ('Philadelphia North','PHN');
INSERT INTO stations(name, station_id) VALUES ('Picayune','PIC');
INSERT INTO stations(name, station_id) VALUES ('Pittsburgh','PGH');
INSERT INTO stations(name, station_id) VALUES ('Pittsfield','PIT');
INSERT INTO stations(name, station_id) VALUES ('Plano','PLO');
INSERT INTO stations(name, station_id) VALUES ('Plattsburgh','PLB');
INSERT INTO stations(name, station_id) VALUES ('Pomona','POS');
INSERT INTO stations(name, station_id) VALUES ('Pontiac','PON');
INSERT INTO stations(name, station_id) VALUES ('Pontiac','PNT');
INSERT INTO stations(name, station_id) VALUES ('Poplar Bluff','PBF');
INSERT INTO stations(name, station_id) VALUES ('Port Henry','POH');
INSERT INTO stations(name, station_id) VALUES ('Port Huron','PTH');
INSERT INTO stations(name, station_id) VALUES ('Port Kent','PRK');
INSERT INTO stations(name, station_id) VALUES ('Portage','POG');
INSERT INTO stations(name, station_id) VALUES ('Portland','POR');
INSERT INTO stations(name, station_id) VALUES ('Portland','PDX');
INSERT INTO stations(name, station_id) VALUES ('Poughkeepsie','POU');
INSERT INTO stations(name, station_id) VALUES ('Prince','PRC');
INSERT INTO stations(name, station_id) VALUES ('Princeton','PCT');
INSERT INTO stations(name, station_id) VALUES ('Princeton Junction','PJC');
INSERT INTO stations(name, station_id) VALUES ('Providence','PVD');
INSERT INTO stations(name, station_id) VALUES ('Provo','PRO');
INSERT INTO stations(name, station_id) VALUES ('Purcell','PUR');
INSERT INTO stations(name, station_id) VALUES ('Quantico','QAN');
INSERT INTO stations(name, station_id) VALUES ('Quincy','QCY');
INSERT INTO stations(name, station_id) VALUES ('Raleigh Union','RGH');
INSERT INTO stations(name, station_id) VALUES ('Randolph','RPH');
INSERT INTO stations(name, station_id) VALUES ('Rantoul','RTL');
INSERT INTO stations(name, station_id) VALUES ('Raton','RAT');
INSERT INTO stations(name, station_id) VALUES ('Red Wing','RDW');
INSERT INTO stations(name, station_id) VALUES ('Redding','RDD');
INSERT INTO stations(name, station_id) VALUES ('Reno','RNO');
INSERT INTO stations(name, station_id) VALUES ('Rensselaer','REN');
INSERT INTO stations(name, station_id) VALUES ('Rhinecliff–Kingston','RHI');
INSERT INTO stations(name, station_id) VALUES ('Richmond','RIC');
INSERT INTO stations(name, station_id) VALUES ('Richmond Staples Mill Road','RVR');
INSERT INTO stations(name, station_id) VALUES ('Richmond Main Street','RVM');
INSERT INTO stations(name, station_id) VALUES ('Riverside','RIV');
INSERT INTO stations(name, station_id) VALUES ('Roanoke','RNK');
INSERT INTO stations(name, station_id) VALUES ('Rochester','ROC');
INSERT INTO stations(name, station_id) VALUES ('Rocklin','RLN');
INSERT INTO stations(name, station_id) VALUES ('Rocky Mount','RMT');
INSERT INTO stations(name, station_id) VALUES ('Rockville','RKV');
INSERT INTO stations(name, station_id) VALUES ('Rome','ROM');
INSERT INTO stations(name, station_id) VALUES ('Roseville','RSV');
INSERT INTO stations(name, station_id) VALUES ('Rouses Point','RSP');
INSERT INTO stations(name, station_id) VALUES ('Royal Oak','ROY');
INSERT INTO stations(name, station_id) VALUES ('Rugby','RUG');
INSERT INTO stations(name, station_id) VALUES ('Rutland','RUD');
INSERT INTO stations(name, station_id) VALUES ('Saco–Biddeford','SAO');
INSERT INTO stations(name, station_id) VALUES ('Sacramento','SAC');
INSERT INTO stations(name, station_id) VALUES ('Salem','SLM');
INSERT INTO stations(name, station_id) VALUES ('Salinas','SNS');
INSERT INTO stations(name, station_id) VALUES ('Salisbury','SAL');
INSERT INTO stations(name, station_id) VALUES ('Salt Lake City','SLC');
INSERT INTO stations(name, station_id) VALUES ('San Antonio','SAS');
INSERT INTO stations(name, station_id) VALUES ('San Bernardino','SNB');
INSERT INTO stations(name, station_id) VALUES ('San Clemente Pier','SNP');
INSERT INTO stations(name, station_id) VALUES ('San Diego Old Town','OLT');
INSERT INTO stations(name, station_id) VALUES ('San Diego Santa Fe Depot','SAN');
INSERT INTO stations(name, station_id) VALUES ('San Jose Diridon','SJC');
INSERT INTO stations(name, station_id) VALUES ('San Juan Capistrano','SNC');
INSERT INTO stations(name, station_id) VALUES ('San Luis Obispo','SLO');
INSERT INTO stations(name, station_id) VALUES ('San Marcos','SMC');
INSERT INTO stations(name, station_id) VALUES ('Sanderson','SND');
INSERT INTO stations(name, station_id) VALUES ('Sandpoint','SPT');
INSERT INTO stations(name, station_id) VALUES ('Sandusky','SKY');
INSERT INTO stations(name, station_id) VALUES ('Sanford','SFA');
INSERT INTO stations(name, station_id) VALUES ('Santa Ana','SNA');
INSERT INTO stations(name, station_id) VALUES ('Santa Barbara','SBA');
INSERT INTO stations(name, station_id) VALUES ('Santa Clara–Great America','GAC');
INSERT INTO stations(name, station_id) VALUES ('Santa Clara–Transit Center','SCC');
INSERT INTO stations(name, station_id) VALUES ('Saratoga Springs','SAR');
INSERT INTO stations(name, station_id) VALUES ('Savannah','SAV');
INSERT INTO stations(name, station_id) VALUES ('Schenectady','SDY');
INSERT INTO stations(name, station_id) VALUES ('Schriever','SCH');
INSERT INTO stations(name, station_id) VALUES ('Seattle King Street','SEA');
INSERT INTO stations(name, station_id) VALUES ('Sebring','SBG');
INSERT INTO stations(name, station_id) VALUES ('Sedalia','SED');
INSERT INTO stations(name, station_id) VALUES ('Selma','SSM');
INSERT INTO stations(name, station_id) VALUES ('Shelby','SBY');
INSERT INTO stations(name, station_id) VALUES ('Simi Valley','SIM');
INSERT INTO stations(name, station_id) VALUES ('Slidell','SDL');
INSERT INTO stations(name, station_id) VALUES ('Solana Beach','SOL');
INSERT INTO stations(name, station_id) VALUES ('South Bend','SOB');
INSERT INTO stations(name, station_id) VALUES ('South Portsmouth–South Shore','SPM');
INSERT INTO stations(name, station_id) VALUES ('Southern Pines','SOP');
INSERT INTO stations(name, station_id) VALUES ('Spartanburg','SPB');
INSERT INTO stations(name, station_id) VALUES ('Spokane','SPK');
INSERT INTO stations(name, station_id) VALUES ('Springfield','SPI');
INSERT INTO stations(name, station_id) VALUES ('Springfield','SPG');
INSERT INTO stations(name, station_id) VALUES ('St. Albans','SAB');
INSERT INTO stations(name, station_id) VALUES ('St. Catharines','SCA');
INSERT INTO stations(name, station_id) VALUES ('St. Cloud','SCD');
INSERT INTO stations(name, station_id) VALUES ('St. Joseph–Benton Harbor','SJM');
INSERT INTO stations(name, station_id) VALUES ('Saint-Lambert','SLQ');
INSERT INTO stations(name, station_id) VALUES ('St. Louis Gateway','STL');
INSERT INTO stations(name, station_id) VALUES ('St. Paul - Minneapolis Union','MSP');
INSERT INTO stations(name, station_id) VALUES ('Stamford','STM');
INSERT INTO stations(name, station_id) VALUES ('Stanley','STN');
INSERT INTO stations(name, station_id) VALUES ('Stanwood','STW');
INSERT INTO stations(name, station_id) VALUES ('Staples','SPL');
INSERT INTO stations(name, station_id) VALUES ('Staunton','STA');
INSERT INTO stations(name, station_id) VALUES ('Stockton Downtown','SKT');
INSERT INTO stations(name, station_id) VALUES ('Stockton San Joaquin Street','SKN');
INSERT INTO stations(name, station_id) VALUES ('Sturtevant','SVT');
INSERT INTO stations(name, station_id) VALUES ('Suisun–Fairfield','SUI');
INSERT INTO stations(name, station_id) VALUES ('Summit','SMT');
INSERT INTO stations(name, station_id) VALUES ('Syracuse','SYR');
INSERT INTO stations(name, station_id) VALUES ('Tacoma Dome','TAC');
INSERT INTO stations(name, station_id) VALUES ('Tampa','TPA');
INSERT INTO stations(name, station_id) VALUES ('Taylor','TAY');
INSERT INTO stations(name, station_id) VALUES ('Temple','TPL');
INSERT INTO stations(name, station_id) VALUES ('Texarkana','TXA');
INSERT INTO stations(name, station_id) VALUES ('Thurmond','THN');
INSERT INTO stations(name, station_id) VALUES ('Ticonderoga','FTC');
INSERT INTO stations(name, station_id) VALUES ('Toccoa','TCA');
INSERT INTO stations(name, station_id) VALUES ('Toledo','TOL');
INSERT INTO stations(name, station_id) VALUES ('Tomah','TOH');
INSERT INTO stations(name, station_id) VALUES ('Topeka','TOP');
INSERT INTO stations(name, station_id) VALUES ('Toronto Union','TWO');
INSERT INTO stations(name, station_id) VALUES ('Trenton','TRE');
INSERT INTO stations(name, station_id) VALUES ('Trinidad','TRI');
INSERT INTO stations(name, station_id) VALUES ('Troy','TRM');
INSERT INTO stations(name, station_id) VALUES ('Truckee','TRU');
INSERT INTO stations(name, station_id) VALUES ('Tucson','TUS');
INSERT INTO stations(name, station_id) VALUES ('Tukwila','TUK');
INSERT INTO stations(name, station_id) VALUES ('Turlock–Denair','TRK');
INSERT INTO stations(name, station_id) VALUES ('Tuscaloosa','TCL');
INSERT INTO stations(name, station_id) VALUES ('Tyrone','TYR');
INSERT INTO stations(name, station_id) VALUES ('Utica','UCA');
INSERT INTO stations(name, station_id) VALUES ('Van Nuys','VNC');
INSERT INTO stations(name, station_id) VALUES ('Vancouver Pacific Central','VAC');
INSERT INTO stations(name, station_id) VALUES ('Vancouver','VAN');
INSERT INTO stations(name, station_id) VALUES ('Ventura','VEC');
INSERT INTO stations(name, station_id) VALUES ('Victorville','VRV');
INSERT INTO stations(name, station_id) VALUES ('Wallingford','WFD');
INSERT INTO stations(name, station_id) VALUES ('Walnut Ridge','WNR');
INSERT INTO stations(name, station_id) VALUES ('Warrensburg','WAR');
INSERT INTO stations(name, station_id) VALUES ('Wasco','WAC');
INSERT INTO stations(name, station_id) VALUES ('Washington Union','WAS');
INSERT INTO stations(name, station_id) VALUES ('Washington','WAH');
INSERT INTO stations(name, station_id) VALUES ('Waterbury–Stowe','WAB');
INSERT INTO stations(name, station_id) VALUES ('Waterloo','WTI');
INSERT INTO stations(name, station_id) VALUES ('Wells','WEM');
INSERT INTO stations(name, station_id) VALUES ('Wenatchee','WEN');
INSERT INTO stations(name, station_id) VALUES ('West Glacier','WGL');
INSERT INTO stations(name, station_id) VALUES ('West Palm Beach','WPB');
INSERT INTO stations(name, station_id) VALUES ('Westerly','WLY');
INSERT INTO stations(name, station_id) VALUES ('Westport','WSP');
INSERT INTO stations(name, station_id) VALUES ('Westwood–Route 128','RTE');
INSERT INTO stations(name, station_id) VALUES ('White River Junction','WRJ');
INSERT INTO stations(name, station_id) VALUES ('White Sulphur Springs','WSS');
INSERT INTO stations(name, station_id) VALUES ('Whitefish','WFH');
INSERT INTO stations(name, station_id) VALUES ('Whitehall','WHL');
INSERT INTO stations(name, station_id) VALUES ('Williamsburg','WBG');
INSERT INTO stations(name, station_id) VALUES ('Williston','WTN');
INSERT INTO stations(name, station_id) VALUES ('Wilmington','WIL');
INSERT INTO stations(name, station_id) VALUES ('Wilson','WLN');
INSERT INTO stations(name, station_id) VALUES ('Windsor','WND');
INSERT INTO stations(name, station_id) VALUES ('Windsor–Mt. Ascutney','WNM');
INSERT INTO stations(name, station_id) VALUES ('Windsor Locks','WNL');
INSERT INTO stations(name, station_id) VALUES ('Winnemucca','WNN');
INSERT INTO stations(name, station_id) VALUES ('Winona','WIN');
INSERT INTO stations(name, station_id) VALUES ('Winslow','WLO');
INSERT INTO stations(name, station_id) VALUES ('Winter Haven','WTH');
INSERT INTO stations(name, station_id) VALUES ('Winter Park Resort','WPR');
INSERT INTO stations(name, station_id) VALUES ('Winter Park','WPK');
INSERT INTO stations(name, station_id) VALUES ('Wisconsin Dells','WDL');
INSERT INTO stations(name, station_id) VALUES ('Wishram','WIH');
INSERT INTO stations(name, station_id) VALUES ('Woburn–Anderson','WOB');
INSERT INTO stations(name, station_id) VALUES ('Wolf Point','WPT');
INSERT INTO stations(name, station_id) VALUES ('Woodbridge','WDB');
INSERT INTO stations(name, station_id) VALUES ('Worcester','WOR');
INSERT INTO stations(name, station_id) VALUES ('Yazoo City','YAZ');
INSERT INTO stations(name, station_id) VALUES ('Yemassee','YEM');
INSERT INTO stations(name, station_id) VALUES ('Yonkers','YNY');
INSERT INTO stations(name, station_id) VALUES ('Yuma','YUM');
INSERT INTO stations(name, station_id) VALUES ('Atmore','ATR');
INSERT INTO stations(name, station_id) VALUES ('Bay St. Louis','BAS');
INSERT INTO stations(name, station_id) VALUES ('Biloxi','BIX');
INSERT INTO stations(name, station_id) VALUES ('Chipley','CIP');
INSERT INTO stations(name, station_id) VALUES ('Crestview','CSV');
INSERT INTO stations(name, station_id) VALUES ('Gulfport','GUF');
INSERT INTO stations(name, station_id) VALUES ('Lake City','LEC');
INSERT INTO stations(name, station_id) VALUES ('Madison','MDO');
INSERT INTO stations(name, station_id) VALUES ('Mobile','MOE');
INSERT INTO stations(name, station_id) VALUES ('Pascagoula','PAG');
INSERT INTO stations(name, station_id) VALUES ('Pensacola','PNS');
INSERT INTO stations(name, station_id) VALUES ('Tallahassee','TLH');
