CREATE TABLE IF NOT EXISTS trains_routes (
    /* station_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    */
    train_number_route_name_id SERIAL PRIMARY KEY,
    amtrak_train_number varchar(5), 
    route_name varchar(64)
);
